In [6]:
import os
import pandas
import numpy
os.listdir()

['Readme.md', '.ipynb_checkpoints', 'smallgray.png', 'Tut4-Numpy.ipynb']

In [8]:
n = numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [9]:
type(n)

numpy.ndarray

In [10]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [12]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [13]:
m = [[123,456,789,101],[],[]]
m

[[123, 456, 789, 101], [], []]

In [15]:
m = numpy.asarray(m)
m

array([[123, 456, 789, 101], [], []], dtype=object)

In [16]:
print(m)

[[123, 456, 789, 101] [] []]
