In [1]:
import os
import pandas
import numpy
import cv2

In [2]:
os.listdir()

['Readme.md',
 'Tut2-OpenCV-Numby.ipynb',
 '.ipynb_checkpoints',
 'smallgray.png',
 'Tut1-Numpy.ipynb']

In [5]:
image = cv2.imread("smallgray.png",0)
image

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [13]:
image_list = [[0, 255, 0, 255, 0],[0, 125, 255, 255, 0],[255, 134, 255,  97, 0]]
image_array = numpy.asarray(image_list)
image_array

array([[  0, 255,   0, 255,   0],
       [  0, 125, 255, 255,   0],
       [255, 134, 255,  97,   0]])

In [14]:
cv2.imwrite("newimage.png", image_array)

True

In [15]:
os.listdir()

['Readme.md',
 'Tut2-OpenCV-Numby.ipynb',
 '.ipynb_checkpoints',
 'smallgray.png',
 'newimage.png',
 'Tut1-Numpy.ipynb']

In [17]:
newImage = cv2.imread("newimage.png",0)
newImage

array([[  0, 255,   0, 255,   0],
       [  0, 125, 255, 255,   0],
       [255, 134, 255,  97,   0]], dtype=uint8)