In [1]:
import os
import pandas
import numpy
import cv2

In [2]:
os.listdir()

['Readme.md',
 'Tut2-OpenCV-Numby.ipynb',
 '.ipynb_checkpoints',
 'smallgray.png',
 'newimage.png',
 'Tut3-slices.ipynb',
 'Tut1-Numpy.ipynb']

In [6]:
a = [1,2,3]
a[0:3]

[1, 2, 3]

In [7]:
image = cv2.imread("smallgray.png",0)
image

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [9]:
image[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [11]:
image[:, 2:4]

array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [12]:
for i in image:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [13]:
for i in image.flat:
    print(i)    

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182
