In [1]:
import os
import pandas
import numpy
import cv2
os.listdir()

['Tut4-numpyArrayFeatures.ipynb',
 'Readme.md',
 'Tut2-OpenCV-Numby.ipynb',
 '.ipynb_checkpoints',
 'smallgray.png',
 'newimage.png',
 'Tut3-slices.ipynb',
 'Tut1-Numpy.ipynb']

In [5]:
image1 = cv2.imread("smallgray.png",0)
image2 = cv2.imread("newimage.png",0)

In [7]:
concatImage = numpy.hstack((image1, image2))
concatImage

array([[187, 158, 104, 121, 143,   0, 255,   0, 255,   0],
       [198, 125, 255, 255, 147,   0, 125, 255, 255,   0],
       [209, 134, 255,  97, 182, 255, 134, 255,  97,   0]], dtype=uint8)

In [9]:
concatImage = numpy.vstack((image1, image2))
concatImage

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [  0, 255,   0, 255,   0],
       [  0, 125, 255, 255,   0],
       [255, 134, 255,  97,   0]], dtype=uint8)

In [10]:
splitArr = numpy.hsplit(concatImage,5)
splitArr

[array([[187],
        [198],
        [209],
        [  0],
        [  0],
        [255]], dtype=uint8), array([[158],
        [125],
        [134],
        [255],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255],
        [  0],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97],
        [255],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182],
        [  0],
        [  0],
        [  0]], dtype=uint8)]

In [14]:
splitArr = numpy.vsplit(concatImage,2)
splitArr

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[  0, 255,   0, 255,   0],
        [  0, 125, 255, 255,   0],
        [255, 134, 255,  97,   0]], dtype=uint8)]